[workspace]
authors = ["Yusaku_MAEDA13 <jagaimo13@gmail.com>"]
channels = ["conda-forge"]
name = "ChromeTools"
platforms = ["win-64"]
version = "0.1.0"

[dependencies]
python = ">=3.10"
selenium = ">=4.10"
webdriver-manager = "*"
pandas = "*"
psutil = "*"
pyautogui = "*"
tqdm = "*"
openpyxl = "*"
requests = "*"
icalendar = "*"
python-dateutil = "*"
